# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Get faster for free.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Jamie Wood
your_link                                 : https://jamiewood.io
your_city                                 : Bristol
email_address                             : hello@tailwind.cc
facebook_username                         : 
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Strava Segments
    description                           : View which of you starred Strava segments currently have favorable weather conditions for beating your record.
    fontawesome_icon_name                 : star
    
  - title                                 : Segment Detail
    description                           : Get in-depth detail on your favorite segments.
    fontawesome_icon_name                 : info-circle

  - title                                 : Coming Soon
    description                           : Push Notifications, Segments Near Me and much more.
    fontawesome_icon_name                 : clock


# Theme Settings
topbar_color                              : "#1a253f"
topbar_transparency                       : 0.1
topbar_title_color                        : "#f1b8ae"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#f1b8ae"

app_title_color                           : "#f1b8ae"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#f1b8ae"
feature_icons_background_color            : "#1a253f"

social_icons_foreground_color             : "#f1b8ae"
social_icons_background_color             : "#1a253f"

footer_text_color                         : "#1a253f"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
